-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphcool.Object exposing (AddToChallengeSolutionsPayload(..), AddToUserSolutionsPayload(..), Challenge(..), ChallengePreviousValues(..), ChallengeSubscriptionPayload(..), InvokeFunctionPayload(..), QueryMeta_(..), Solution(..), SolutionPreviousValues(..), SolutionSubscriptionPayload(..), User(..), UserPreviousValues(..), UserSubscriptionPayload(..))


type AddToChallengeSolutionsPayload
    = AddToChallengeSolutionsPayload


type AddToUserSolutionsPayload
    = AddToUserSolutionsPayload


type Challenge
    = Challenge


type ChallengePreviousValues
    = ChallengePreviousValues


type ChallengeSubscriptionPayload
    = ChallengeSubscriptionPayload


type InvokeFunctionPayload
    = InvokeFunctionPayload


type QueryMeta_
    = QueryMeta_


type Solution
    = Solution


type SolutionPreviousValues
    = SolutionPreviousValues


type SolutionSubscriptionPayload
    = SolutionSubscriptionPayload


type User
    = User


type UserPreviousValues
    = UserPreviousValues


type UserSubscriptionPayload
    = UserSubscriptionPayload
