-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphcool.Object exposing (AddToChallengeSolutionsPayload(..), AddToUserSolutionsPayload(..), AuthenticateUserPayload(..), Challenge(..), ChallengePreviousValues(..), ChallengeSubscriptionPayload(..), CheckAnswerPayload(..), GetAnswerPayload(..), InvokeFunctionPayload(..), LoggedInUserPayload(..), QueryMeta_(..), Solution(..), SolutionPreviousValues(..), SolutionSubscriptionPayload(..), User(..), UserPreviousValues(..), UserSubscriptionPayload(..))


type AddToChallengeSolutionsPayload
    = AddToChallengeSolutionsPayload


type AddToUserSolutionsPayload
    = AddToUserSolutionsPayload


type AuthenticateUserPayload
    = AuthenticateUserPayload


type Challenge
    = Challenge


type ChallengePreviousValues
    = ChallengePreviousValues


type ChallengeSubscriptionPayload
    = ChallengeSubscriptionPayload


type CheckAnswerPayload
    = CheckAnswerPayload


type GetAnswerPayload
    = GetAnswerPayload


type InvokeFunctionPayload
    = InvokeFunctionPayload


type LoggedInUserPayload
    = LoggedInUserPayload


type QueryMeta_
    = QueryMeta_


type Solution
    = Solution


type SolutionPreviousValues
    = SolutionPreviousValues


type SolutionSubscriptionPayload
    = SolutionSubscriptionPayload


type User
    = User


type UserPreviousValues
    = UserPreviousValues


type UserSubscriptionPayload
    = UserSubscriptionPayload
