-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphcool.ScalarCodecs exposing (DateTime, Id, codecs)

import Graphcool.Scalar exposing (defaultCodecs)
import Json.Decode as Decode exposing (Decoder)


type alias DateTime =
    Graphcool.Scalar.DateTime


type alias Id =
    Graphcool.Scalar.Id


codecs : Graphcool.Scalar.Codecs DateTime Id
codecs =
    Graphcool.Scalar.defineCodecs
        { codecDateTime = defaultCodecs.codecDateTime
        , codecId = defaultCodecs.codecId
        }
