-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphcool.Enum.ModelMutationType_ exposing (ModelMutationType_(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type ModelMutationType_
    = Created
    | Updated
    | Deleted


list : List ModelMutationType_
list =
    [ Created, Updated, Deleted ]


decoder : Decoder ModelMutationType_
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "CREATED" ->
                        Decode.succeed Created

                    "UPDATED" ->
                        Decode.succeed Updated

                    "DELETED" ->
                        Decode.succeed Deleted

                    _ ->
                        Decode.fail ("Invalid ModelMutationType_ type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : ModelMutationType_ -> String
toString enum =
    case enum of
        Created ->
            "CREATED"

        Updated ->
            "UPDATED"

        Deleted ->
            "DELETED"
