-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphcool.Enum.SolutionOrderBy exposing (SolutionOrderBy(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type SolutionOrderBy
    = Attempts_ASC
    | Attempts_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | Id_ASC
    | Id_DESC
    | Solved_ASC
    | Solved_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC


list : List SolutionOrderBy
list =
    [ Attempts_ASC, Attempts_DESC, CreatedAt_ASC, CreatedAt_DESC, Id_ASC, Id_DESC, Solved_ASC, Solved_DESC, UpdatedAt_ASC, UpdatedAt_DESC ]


decoder : Decoder SolutionOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "attempts_ASC" ->
                        Decode.succeed Attempts_ASC

                    "attempts_DESC" ->
                        Decode.succeed Attempts_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "solved_ASC" ->
                        Decode.succeed Solved_ASC

                    "solved_DESC" ->
                        Decode.succeed Solved_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid SolutionOrderBy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : SolutionOrderBy -> String
toString enum =
    case enum of
        Attempts_ASC ->
            "attempts_ASC"

        Attempts_DESC ->
            "attempts_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Solved_ASC ->
            "solved_ASC"

        Solved_DESC ->
            "solved_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"
