-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphcool.Enum.UserOrderBy exposing (UserOrderBy(..), decoder, list, toString)

import Json.Decode as Decode exposing (Decoder)


type UserOrderBy
    = Auth0UserId_ASC
    | Auth0UserId_DESC
    | CreatedAt_ASC
    | CreatedAt_DESC
    | Id_ASC
    | Id_DESC
    | Nickname_ASC
    | Nickname_DESC
    | Picture_ASC
    | Picture_DESC
    | Role_ASC
    | Role_DESC
    | UpdatedAt_ASC
    | UpdatedAt_DESC


list : List UserOrderBy
list =
    [ Auth0UserId_ASC, Auth0UserId_DESC, CreatedAt_ASC, CreatedAt_DESC, Id_ASC, Id_DESC, Nickname_ASC, Nickname_DESC, Picture_ASC, Picture_DESC, Role_ASC, Role_DESC, UpdatedAt_ASC, UpdatedAt_DESC ]


decoder : Decoder UserOrderBy
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "auth0UserId_ASC" ->
                        Decode.succeed Auth0UserId_ASC

                    "auth0UserId_DESC" ->
                        Decode.succeed Auth0UserId_DESC

                    "createdAt_ASC" ->
                        Decode.succeed CreatedAt_ASC

                    "createdAt_DESC" ->
                        Decode.succeed CreatedAt_DESC

                    "id_ASC" ->
                        Decode.succeed Id_ASC

                    "id_DESC" ->
                        Decode.succeed Id_DESC

                    "nickname_ASC" ->
                        Decode.succeed Nickname_ASC

                    "nickname_DESC" ->
                        Decode.succeed Nickname_DESC

                    "picture_ASC" ->
                        Decode.succeed Picture_ASC

                    "picture_DESC" ->
                        Decode.succeed Picture_DESC

                    "role_ASC" ->
                        Decode.succeed Role_ASC

                    "role_DESC" ->
                        Decode.succeed Role_DESC

                    "updatedAt_ASC" ->
                        Decode.succeed UpdatedAt_ASC

                    "updatedAt_DESC" ->
                        Decode.succeed UpdatedAt_DESC

                    _ ->
                        Decode.fail ("Invalid UserOrderBy type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representating the Enum to a string that the GraphQL server will recognize.
-}
toString : UserOrderBy -> String
toString enum =
    case enum of
        Auth0UserId_ASC ->
            "auth0UserId_ASC"

        Auth0UserId_DESC ->
            "auth0UserId_DESC"

        CreatedAt_ASC ->
            "createdAt_ASC"

        CreatedAt_DESC ->
            "createdAt_DESC"

        Id_ASC ->
            "id_ASC"

        Id_DESC ->
            "id_DESC"

        Nickname_ASC ->
            "nickname_ASC"

        Nickname_DESC ->
            "nickname_DESC"

        Picture_ASC ->
            "picture_ASC"

        Picture_DESC ->
            "picture_DESC"

        Role_ASC ->
            "role_ASC"

        Role_DESC ->
            "role_DESC"

        UpdatedAt_ASC ->
            "updatedAt_ASC"

        UpdatedAt_DESC ->
            "updatedAt_DESC"
