-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphcool.Object.ChallengeSubscriptionPayload exposing (mutation, node, previousValues, updatedFields)

import Graphcool.Enum.ModelMutationType_
import Graphcool.InputObject
import Graphcool.Interface
import Graphcool.Object
import Graphcool.Scalar
import Graphcool.ScalarCodecs
import Graphcool.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


mutation : SelectionSet Graphcool.Enum.ModelMutationType_.ModelMutationType_ Graphcool.Object.ChallengeSubscriptionPayload
mutation =
    Object.selectionForField "Enum.ModelMutationType_.ModelMutationType_" "mutation" [] Graphcool.Enum.ModelMutationType_.decoder


node : SelectionSet decodesTo Graphcool.Object.Challenge -> SelectionSet (Maybe decodesTo) Graphcool.Object.ChallengeSubscriptionPayload
node object_ =
    Object.selectionForCompositeField "node" [] object_ (identity >> Decode.nullable)


updatedFields : SelectionSet (Maybe (List String)) Graphcool.Object.ChallengeSubscriptionPayload
updatedFields =
    Object.selectionForField "(Maybe (List String))" "updatedFields" [] (Decode.string |> Decode.list |> Decode.nullable)


previousValues : SelectionSet decodesTo Graphcool.Object.ChallengePreviousValues -> SelectionSet (Maybe decodesTo) Graphcool.Object.ChallengeSubscriptionPayload
previousValues object_ =
    Object.selectionForCompositeField "previousValues" [] object_ (identity >> Decode.nullable)
