-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Graphcool.Object.GetAnswerPayload exposing (answer, discussionUrl)

import Graphcool.InputObject
import Graphcool.Interface
import Graphcool.Object
import Graphcool.Scalar
import Graphcool.ScalarCodecs
import Graphcool.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


answer : SelectionSet (Maybe String) Graphcool.Object.GetAnswerPayload
answer =
    Object.selectionForField "(Maybe String)" "answer" [] (Decode.string |> Decode.nullable)


discussionUrl : SelectionSet (Maybe String) Graphcool.Object.GetAnswerPayload
discussionUrl =
    Object.selectionForField "(Maybe String)" "discussionUrl" [] (Decode.string |> Decode.nullable)
